<a href="https://colab.research.google.com/github/saireddy2106/Machine_learning/blob/main/NumPy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
list1 = [1,2,3,4,5]
print(list1);
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
a = np.array([9,8,7,6,5])
print(a)

[9 8 7 6 5]


In [ ]:
a.shape

(5,)

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
b.shape  #(2,3) 2->num of rows 3->num of columns

(2, 3)

In [ ]:
c = np.array([[1,2,3,4],[5,6,7,8]],dtype=float)  #by default data type is int so if we explicitly mention dtype=float it will give as float
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholders in numpy arrays

In [ ]:
#create a numpy array of zeros
x = np.zeros((3,4)) #3 rows and 4  cols
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#create an array of ones
y = np.ones((2,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#create an array of particular values
z = np.full((3,4),4)
print(z)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [ ]:
q = np.full((2,4),3)
print(q)
print(q.shape)
print(q.size)
print(q.ndim)

[[3 3 3 3]
 [3 3 3 3]]
(2, 4)
8
2


In [ ]:
#create a identity matrix
a=np.eye(3) #identity rows and cols should be equal
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#create an array of random values
b = np.random.random((3,4))
print(b)

[[0.05616054 0.75888537 0.47617453 0.03587355]
 [0.95476494 0.9311232  0.22183171 0.32405711]
 [0.92756094 0.58761594 0.4341216  0.76747499]]


In [ ]:
t = np.random.random((4,5))
print(t)

[[0.97201892 0.44047523 0.54005592 0.04811184 0.59504911]
 [0.74470367 0.47977371 0.59456899 0.68673788 0.04170822]
 [0.02592143 0.48883329 0.50523975 0.98038415 0.03075187]
 [0.32950827 0.77551296 0.8909616  0.08902051 0.03058744]]


In [ ]:
u = np.random.randint(1,20,(3,4))
print(u)

[[16  4  6  3]
 [ 4  7  9 19]
 [17  9  7 10]]


In [ ]:
#create an random array with integer values
c = np.random.randint(3,10,(4,5)) #3,10 is range of integer random values and 4,5 is size of rows and cols
print(c)

[[8 6 5 9 4]
 [3 9 7 6 6]
 [6 7 6 7 9]
 [3 7 8 7 3]]


In [ ]:
#create an array of equally spaced values and certain values
d = np.linspace(10,30,6) #range btw 10 and 30 with 5 values
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
# equally spaced btw range with specified gap
x = np.arange(1,30,4)
print(x)

[ 1  5  9 13 17 21 25 29]


In [ ]:
o = np.arange(1,50,10)
print(o)

[ 1 11 21 31 41]


In [ ]:
#convert a list to a numpy array
list1 = [1,2,3,4,5]
np_array = np.asarray(list1)
print(list1)
print(np_array)
type(np_array)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


numpy.ndarray

In [ ]:
lis = [1,2,3,4,5]
np_arr = np.asarray(lis)
print(lis)
print(np_arr)
type(np_arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


numpy.ndarray

Analysing a nupy array

In [ ]:
x = np.random.randint(2,20,(4,5))
print(x)

[[17 16 12 14 10]
 [15  3 16  3  9]
 [ 8 13  7 16  2]
 [ 2  6 19 12  8]]


In [ ]:
#to find dimessions of an array
x.shape

(4, 5)

In [ ]:
#num of dimesions
print(x.ndim)

2


In [ ]:
#number of elements present in an array
print(x.size)

20


In [ ]:
#to check datatype of values in the array
print(x.dtype)

int64


Mathematical operations in an array

In [ ]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]
print(list1+list2) #adds two list

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[8 2 7]
 [5 0 8]
 [6 8 5]]
[[10 15 15]
 [11 19 19]
 [19 13 10]]


In [ ]:
print(a+b) #in case of numpy array it gives element wise addition

[[18 17 22]
 [16 19 27]
 [25 21 15]]


In [ ]:
print(a-b)

[[ -2 -13  -8]
 [ -6 -19 -11]
 [-13  -5  -5]]


In [ ]:
print(a*b)

[[ 80  30 105]
 [ 55   0 152]
 [114 104  50]]


In [ ]:
print(a/b)

[[0.8        0.13333333 0.46666667]
 [0.45454545 0.         0.42105263]
 [0.31578947 0.61538462 0.5       ]]


instead of above we can also those operations like below

In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[13 25 20]
 [16 23 26]
 [26 14 19]]
[[-11  -9 -18]
 [ -4  -5 -10]
 [-10 -10  -9]]
[[ 12 136  19]
 [ 60 126 144]
 [144  24  70]]
[[0.08333333 0.47058824 0.05263158]
 [0.6        0.64285714 0.44444444]
 [0.44444444 0.16666667 0.35714286]]


In [ ]:
nums = np.random.randint(1,20,(2,3))
print(nums)
print(nums.shape)

[[ 5  4 17]
 [ 7  6  5]]
(2, 3)


In [ ]:
#transpose
trans = np.transpose(nums)
print(trans)
print(trans.shape)

[[ 5  7]
 [ 4  6]
 [17  5]]
(3, 2)


In [ ]:
#another way of transpose
trans2 = nums.T
print(trans2)
print(trans2.shape)

[[ 5  7]
 [ 4  6]
 [17  5]]
(3, 2)


In [ ]:
#reshaping the array

listt = np.random.randint(1,15,(3,5))
print(listt)
print(listt.shape)

[[ 1  6  4  1  5]
 [12 12  4  3 12]
 [ 3  6 12  6 11]]
(3, 5)


In [ ]:
num = listt.reshape(5,3)
print(num)
print(num.shape)

[[ 1  6  4]
 [ 1  5 12]
 [12  4  3]
 [12  3  6]
 [12  6 11]]
(5, 3)
